name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Core:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - run: go version
    - name: Run smoke tests
      run: make test-smoke

