name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: install git gcc
      run: |
        sudo yum install -y git gcc
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - run: go version
    - run: date
    - name: Run tests
      run: TEST_OPTS="PASSES='fmt build unit integration_e2e'" make test
